### ISSUE TITLE
React-Virtualized support?

### ISSUE THREAD

**Issue by meds** [wadackel/react-stack-grid#30]
would it be possible to add support for [react-virtualized](https://github.com/bvaughn/react-virtualized)? Would help greatly in rendering large stack grids efficiently.

**Comment by tsuyoshiwada** [comment]
Hi @meds Sorry for the late reply...

You're absolutely right., virtual scrolling is very attractive in terms of performance :+1:
But, I have considered support once, but I have abandoned it because I can not get much work time...

If you are interested in improving `react-stack-grid`, we are always waiting for PR :smile:

**Comment by meds** [comment]
No worries I might give it a look :)

**Comment by tsuyoshiwada** [comment]
Thanks :+1:
